using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

[Serializable]
public class StoryResourceDefinition
{
    public string path;
    public string kind;
    public string source = "auto";
    public string metadata;
}

[Serializable]
public class StoryActorReferenceDocument
{
    public string actorId;
}

[Serializable]
public class StoryMapReferenceDocument
{
    public int mapId;
}

[Serializable]
public class StorySceneResourceDocument
{
    public string id;
    public string name;
    public string backgroundResourcePath;
    public string defaultBgmResourcePath;

    public string displayName => string.IsNullOrWhiteSpace(name) ? id : name;
}

[Serializable]
public class StorySceneDocument
{
    public string id;
    public int mapId;
    public string sceneResourceId;
    public string bgmResourcePath;
    // 进入当前场景时使用的背景转场。
    public StoryTransitionDocument transition;
    public StorySceneActorLayoutDocument[] actors;
    public StoryLayoutDocument layout;

    public StorySceneActorLayoutDocument GetActorLayout(string actorId)
    {
        if (string.IsNullOrWhiteSpace(actorId) || actors == null)
            return null;

        return actors.FirstOrDefault(x => x != null && string.Equals(x.actorId, actorId, StringComparison.OrdinalIgnoreCase));
    }
}

[Serializable]
public class StoryTransitionDocument
{
    public string type = "none";
    public float duration = .35f;

    public string normalizedType
    {
        get
        {
            string value = (type ?? string.Empty).Trim().ToLowerInvariant();
            switch (value)
            {
                case "inherit":
                case "fade":
                case "crossfade":
                case "wipeleft":
                case "wiperight":
                case "wipeup":
                case "wipedown":
                case "pushleft":
                case "pushright":
                case "pushup":
                case "pushdown":
                case "zoomcross":
                case "radial":
                    return value;
                default:
                    return "none";
            }
        }
    }

    public float normalizedDuration => Math.Max(.1f, Math.Min(2f, duration <= 0f ? .35f : duration));
}

[Serializable]
public class StorySceneActorLayoutDocument
{
    public string actorId;
    public string placementMode = "auto";
    public string side = "left";
    public int order;
    public float scale = 1f;
    public bool faceLeft = true;
    public bool flipIcon;
    public float x;
    public float y;

    public string normalizedPlacementMode => string.Equals(placementMode, "manual", StringComparison.OrdinalIgnoreCase) ? "manual" : "auto";
    public string normalizedSide => string.Equals(side, "right", StringComparison.OrdinalIgnoreCase) ? "right" : "left";
}

[Serializable]
public class StoryConditionDocument
{
    public string type;
    public bool negated;
    public string pointId;
    public string commandId;
    public string choiceId;
    public string optionId;
    public string[] optionSequence;
    public string flag;
    public string value;
    public int missionId;
    public string missionState;
}

[Serializable]
public class ConditionGroupDocument
{
    public string operatorType = "AND";
    public StoryConditionDocument[] conditions;
    public StoryConditionClauseDocument[] clauses;

    public bool hasConditions => (clauses ?? Array.Empty<StoryConditionClauseDocument>())
            .Any(clause => clause?.conditions != null && clause.conditions.Length > 0)
        || (conditions != null && conditions.Length > 0);
}

[Serializable]
public class StoryConditionClauseDocument
{
    public StoryConditionDocument[] conditions;
}

/// <summary>
/// 剧情点完成后的下一跳。条件连接按数组顺序依次判定；默认连接始终作为最后的兜底。
/// </summary>
[Serializable]
public class StoryNodeTransitionDocument
{
    public string transitionId;
    public string targetType = "node";
    public string targetNodeId;
    public bool isDefault;
    public bool isAutoGenerated;
    public ConditionGroupDocument condition;
    // 仅用于读取 schemaVersion 5 及更早版本；新版转场统一存放在目标 StorySceneDocument。
    public StoryTransitionDocument transition;

    public bool isEnd => string.Equals(targetType?.Trim(), "end", StringComparison.OrdinalIgnoreCase);
}

[Serializable]
public class StoryTextStyleDocument
{
    public string font;
    public int fontSize;
    public string textColor;
    public string outlineColor;
    public float outlineWidth;
    public bool bold = false;
}

[Serializable]
public class StoryDocument
{
    public int schemaVersion = 9;
    public string status = "published";
    public string id;
    public string title;
    public string summary;
    public string entry = "start";
    public StoryLayoutDocument layout;
    public StoryTextStyleDocument style;
    public StoryMissionDocument mission;
    public bool replayable = true;
    public StoryResourceDefinition[] resourceDefinitions;
    public StorySceneResourceDocument[] sceneResources;
    public StoryActorDocument[] actors;
    public StoryNodeDocument[] nodes;

    public bool isDraft => string.Equals(status, "draft", StringComparison.OrdinalIgnoreCase);
    public string normalizedStatus => isDraft ? "draft" : "published";
    public bool HasSupportedStatus => string.IsNullOrWhiteSpace(status)
        || isDraft
        || string.Equals(status, "published", StringComparison.OrdinalIgnoreCase);
    public bool IsValid => StoryValidator.Validate(this, out _);

    public MissionInfo ToMissionInfo()
    {
        if (isDraft || !IsValid)
            return null;

        return new MissionInfo
        {
            id = mission.id,
            typeId = (int)MissionType.Mod,
            replayable = replayable && mission.replayable,
            autoCompleteStory = true,
            title = string.IsNullOrEmpty(title) ? mission.title : title,
            checkpoints = new List<MissionCheckpoint>
            {
                new MissionCheckpoint
                {
                    id = "default",
                    mapId = mission.mapId,
                    storyId = "mod:" + id,
                    intro = string.IsNullOrEmpty(summary) ? mission.summary : summary,
                }
            },
            rewards = new List<Item>(),
        };
    }

    public StoryScript ToScript()
    {
        StoryScript script = new StoryScript
        {
            layout = layout,
            textStyle = style
        };
        foreach (StoryResourceDefinition resource in resourceDefinitions ?? Array.Empty<StoryResourceDefinition>())
        {
            if (resource == null || string.IsNullOrWhiteSpace(resource.path))
                continue;

            script.resourceSources[resource.path] = string.IsNullOrWhiteSpace(resource.source)
                ? "auto"
                : resource.source.Trim().ToLower();
        }
        if (nodes == null)
            return script;

        List<StoryNodeDocument> orderedNodes = GetOrderedNodes();
        List<StoryNodeDocument> sequenceNodes = orderedNodes
            .Where(node => node != null && !node.isBranch)
            .ToList();

        foreach (StoryNodeDocument node in orderedNodes)
        {
            if (node == null || string.IsNullOrEmpty(node.id))
                continue;

            script.labels[node.id] = script.commands.Count;
            bool isSceneOpening = false;
            StoryCommandDocument[] nodeCommands = node.commands ?? Array.Empty<StoryCommandDocument>();
            for (int commandIndex = 0; commandIndex < nodeCommands.Length; commandIndex++)
            {
                StoryCommand parsed = nodeCommands[commandIndex]?.ToCommand(this, node);
                if (parsed != null)
                {
                    parsed.pointId = node.id;
                    if (parsed.type == StoryCommandType.Scene)
                    {
                        isSceneOpening = true;
                    }
                    else if (parsed.type == StoryCommandType.Show && isSceneOpening)
                    {
                        // 场景命令已按场景角色表完成首次显示；跳过旧草稿自动生成的冗余 show。
                        continue;
                    }
                    else
                    {
                        isSceneOpening = false;
                    }

                    if (string.IsNullOrEmpty(parsed.commandId))
                        parsed.commandId = node.id + ":" + commandIndex;
                    script.commands.Add(parsed);
                }
            }

            AppendNodeTransitions(script, node);
            if (!HasExplicitDefaultTransition(node))
            {
                string fallbackNodeId = GetDefaultFlowTarget(node, sequenceNodes);
                AppendNodeFlowFallback(script, node, fallbackNodeId);
            }
        }

        return script;
    }

    public StoryActorDocument GetActor(string actorId)
    {
        if (string.IsNullOrEmpty(actorId) || actors == null)
            return null;

        return actors.FirstOrDefault(x => x != null && x.id == actorId);
    }

    public StorySceneResourceDocument GetSceneResource(string resourceId)
    {
        if (string.IsNullOrWhiteSpace(resourceId) || sceneResources == null)
            return null;

        return sceneResources.FirstOrDefault(value => value != null
            && string.Equals(value.id, resourceId, StringComparison.OrdinalIgnoreCase));
    }

    private List<StoryNodeDocument> GetOrderedNodes()
    {
        StoryNodeDocument[] allNodes = nodes ?? Array.Empty<StoryNodeDocument>();
        List<StoryNodeDocument> orderedNodes = allNodes
            .Where(node => node != null && !node.isBranch)
            .ToList();
        StoryNodeDocument entryNode = orderedNodes.FirstOrDefault(node => node.id == entry);
        if (entryNode != null)
        {
            orderedNodes.Remove(entryNode);
            orderedNodes.Insert(0, entryNode);
        }

        orderedNodes.AddRange(allNodes.Where(node => node != null && node.isBranch));
        return orderedNodes;
    }

    private static void AppendNodeTransitions(StoryScript script, StoryNodeDocument node)
    {
        StoryNodeTransitionDocument[] transitions = node.transitions ?? Array.Empty<StoryNodeTransitionDocument>();
        foreach (StoryNodeTransitionDocument transition in transitions
                     .Where(value => value != null && !value.isDefault)
                     .Concat(transitions.Where(value => value != null && value.isDefault)))
        {
            if (!transition.isEnd && string.IsNullOrWhiteSpace(transition.targetNodeId))
                continue;

            // 条件分支不允许以空条件组退化为无条件跳转。
            if (!transition.isDefault && (transition.condition == null || !transition.condition.hasConditions))
                continue;

            script.commands.Add(new StoryCommand
            {
                commandId = node.id + ":transition:" + (transition.transitionId ?? transition.targetNodeId),
                pointId = node.id,
                type = transition.isEnd ? StoryCommandType.End : StoryCommandType.Jump,
                args = transition.isEnd ? null : transition.targetNodeId,
                condition = transition.isDefault ? null : transition.condition,
            });
        }
    }

    private static bool HasExplicitDefaultTransition(StoryNodeDocument node)
    {
        return (node?.transitions ?? Array.Empty<StoryNodeTransitionDocument>())
            .Any(transition => transition != null
                && transition.isDefault
                && (transition.isEnd || !string.IsNullOrWhiteSpace(transition.targetNodeId)));
    }

    private static string GetDefaultFlowTarget(StoryNodeDocument node, List<StoryNodeDocument> sequenceNodes)
    {
        if (node == null)
            return string.Empty;

        if (node.isBranch)
            return node.fallbackNodeId;

        int nodeIndex = sequenceNodes.IndexOf(node);
        if (nodeIndex < 0 || nodeIndex + 1 >= sequenceNodes.Count)
            return string.Empty;

        return sequenceNodes[nodeIndex + 1]?.id;
    }

    private static void AppendNodeFlowFallback(StoryScript script, StoryNodeDocument node, string fallbackNodeId)
    {
        if (script == null || node == null)
            return;

        if (!string.IsNullOrWhiteSpace(fallbackNodeId))
        {
            script.commands.Add(new StoryCommand
            {
                commandId = node.id + ":flow",
                pointId = node.id,
                type = StoryCommandType.Jump,
                args = fallbackNodeId,
            });
            return;
        }

        script.commands.Add(new StoryCommand
        {
            commandId = node.id + ":flow:end",
            pointId = node.id,
            type = StoryCommandType.End,
        });
    }
}

[Serializable]
public class StoryMissionDocument
{
    public int id;
    public string title;
    public bool replayable = true;
    public int mapId;
    public int[] mapIds;
    public string summary;
}

[Serializable]
public class StoryActorDocument
{
    public string id;
    public string actorType = "pet";
    public string petId;
    public string npcId;
    public string name;
    public string sprite;
    public string icon;
    public string battleSprite;
    public string sourceFacing = "right";
    public string iconMode = "separate";
    public string independentIcon;
    public float iconCropX;
    public float iconCropY;
    public float iconCropWidth;
    public float iconCropHeight;
    public float defaultScale = 1f;
    public bool defaultFaceLeft = true;
    public bool defaultFlipIcon;

    public string displayName => string.IsNullOrEmpty(name) ? id : name;
    public string displaySprite => string.IsNullOrEmpty(sprite) ? icon : sprite;
    public bool sourceFacesLeft => string.Equals(sourceFacing, "left", StringComparison.OrdinalIgnoreCase);
    public bool usesPortraitIcon => string.Equals(iconMode, "crop", StringComparison.OrdinalIgnoreCase);
    public Rect normalizedIconCrop => StorySpriteResolver.NormalizeCrop(
        iconCropX, iconCropY, iconCropWidth, iconCropHeight);
}

[Serializable]
public class StoryLayoutDocument
{
    public string autoLayoutMode = "invertedV";
    public float actorSpacing;
    public float actorHeight;
    public float actorBottom;
    public float centerGap;
    public float stackOffset;
}

[Serializable]
public class StoryNodeDocument
{
    public string id;
    public string displayName;
    public string flowRole = "sequence";
    public string fallbackNodeId;
    public StoryMapReferenceDocument[] mapReferences;
    public StoryActorReferenceDocument[] actorReferences;
    public StorySceneDocument[] scenes;
    public StoryTextStyleDocument style;
    public StoryCommandDocument[] commands;
    public StoryNodeTransitionDocument[] transitions;

    public string normalizedFlowRole => string.Equals(flowRole, "branch", StringComparison.OrdinalIgnoreCase)
        ? "branch"
        : "sequence";
    public bool isBranch => string.Equals(normalizedFlowRole, "branch", StringComparison.OrdinalIgnoreCase);
    public bool defaultEnds
    {
        get
        {
            StoryNodeTransitionDocument defaultTransition = (transitions ?? Array.Empty<StoryNodeTransitionDocument>())
                .FirstOrDefault(transition => transition != null && transition.isDefault);
            if (defaultTransition != null)
                return defaultTransition.isEnd;

            return isBranch && string.IsNullOrWhiteSpace(fallbackNodeId);
        }
    }
    public bool hasEndingPath => defaultEnds
        || (transitions ?? Array.Empty<StoryNodeTransitionDocument>()).Any(transition => transition != null && transition.isEnd)
        || (commands ?? Array.Empty<StoryCommandDocument>()).Any(command => command != null
            && string.Equals(command.type, "end", StringComparison.OrdinalIgnoreCase)
            && (command.condition == null || !command.condition.hasConditions));
    public bool isEnding
    {
        get
        {
            bool hasUnconditionalEndCommand = (commands ?? Array.Empty<StoryCommandDocument>())
                .Any(command => command != null
                    && string.Equals(command.type, "end", StringComparison.OrdinalIgnoreCase)
                    && (command.condition == null || !command.condition.hasConditions));
            bool hasNodeTransition = (transitions ?? Array.Empty<StoryNodeTransitionDocument>())
                .Any(transition => transition != null && !transition.isEnd);
            bool hasCommandJump = (commands ?? Array.Empty<StoryCommandDocument>())
                .Any(command => command != null
                    && string.Equals(command.type, "jump", StringComparison.OrdinalIgnoreCase)
                    && !string.IsNullOrWhiteSpace(command.target));
            bool hasChoiceTarget = (commands ?? Array.Empty<StoryCommandDocument>())
                .SelectMany(command => command?.choices ?? Array.Empty<StoryChoiceDocument>())
                .Any(choice => choice != null && !string.IsNullOrWhiteSpace(choice.target));
            return (defaultEnds || hasUnconditionalEndCommand)
                && !hasNodeTransition
                && !hasCommandJump
                && !hasChoiceTarget;
        }
    }

    public StorySceneDocument GetScene(string sceneId)
    {
        if (string.IsNullOrWhiteSpace(sceneId) || scenes == null)
            return null;

        return scenes.FirstOrDefault(x => x != null && string.Equals(x.id, sceneId, StringComparison.OrdinalIgnoreCase));
    }
}

[Serializable]
public class StoryCommandDocument
{
    public string commandId;
    public string type;
    public string choiceOriginalType;
    public string choiceId;
    public string sceneId;
    public int mapId;
    public string bgmResourcePath;
    public string bg;
    public StoryTransitionDocument transition;
    public string actor;
    public string expression;
    public string text;
    public string target;
    public string args;
    public StoryLayoutDocument layout;
    public float actorSpacing;
    public float actorHeight;
    public float actorBottom;
    public float centerGap;
    public float stackOffset;
    public StoryChoiceDocument[] choices;
    public ConditionGroupDocument condition;
    public ConditionGroupDocument displayCondition;

    public StoryCommand ToCommand(StoryDocument document, StoryNodeDocument node = null)
    {
        string commandType = (type ?? string.Empty).Trim().ToLower();
        StoryCommand command = new StoryCommand();
        command.commandId = commandId;
        command.choiceId = choiceId;
        command.condition = condition;
        command.displayCondition = displayCondition;
        switch (commandType)
        {
            case "scene":
                command.type = StoryCommandType.Scene;
                StorySceneDocument scene = node?.GetScene(sceneId);
                StorySceneResourceDocument sceneResource = document?.GetSceneResource(scene?.sceneResourceId);
                command.mapId = sceneResource != null
                    ? 0
                    : scene != null && scene.mapId != 0 ? scene.mapId : mapId;
                command.bgmResourcePath = !string.IsNullOrEmpty(scene?.bgmResourcePath)
                    ? scene.bgmResourcePath
                    : !string.IsNullOrEmpty(sceneResource?.defaultBgmResourcePath)
                        ? sceneResource.defaultBgmResourcePath
                        : bgmResourcePath;
                command.args = !string.IsNullOrEmpty(sceneResource?.backgroundResourcePath)
                    ? sceneResource.backgroundResourcePath
                    : string.IsNullOrEmpty(bg)
                        ? (command.mapId != 0 ? "Maps/bg/" + command.mapId : args)
                        : bg;
                command.layout = scene?.layout ?? GetSceneLayout();
                command.actorLayouts = scene?.actors;
                command.transition = scene?.transition ?? transition;
                command.sceneActors = (scene?.actors ?? Array.Empty<StorySceneActorLayoutDocument>())
                    .Where(layout => layout != null && !string.IsNullOrWhiteSpace(layout.actorId))
                    .Select(layout => document?.GetActor(layout.actorId))
                    .Where(actorDocument => actorDocument != null)
                    .ToArray();
                return command;
            case "show":
                command.type = StoryCommandType.Show;
                command.actorId = actor;
                command.actorInfo = document?.GetActor(actor);
                command.args = GetActorShowArgs(document);
                return command.actorInfo == null && string.IsNullOrEmpty(command.args) ? null : command;
            case "hide":
                command.type = StoryCommandType.Hide;
                command.actorId = actor;
                command.args = string.IsNullOrEmpty(actor) ? args : actor;
                return command;
            case "say":
                command.type = StoryCommandType.Say;
                command.actorId = actor;
                command.actorInfo = document?.GetActor(actor);
                command.speaker = GetActorName(document);
                command.expression = expression;
                command.text = text;
                return command;
            case "narrate":
                command.type = StoryCommandType.Narrate;
                command.text = text;
                return command;
            case "choice":
                command.type = StoryCommandType.Choice;
                command.actorId = actor;
                command.actorInfo = document?.GetActor(actor);
                command.speaker = GetActorName(document);
                command.expression = expression;
                command.text = text;
                command.choices = (choices ?? Array.Empty<StoryChoiceDocument>())
                    .Select(x => x?.ToChoice())
                    .Where(x => x != null)
                    .ToList();
                return command;
            case "jump":
                command.type = StoryCommandType.Jump;
                command.args = target;
                return command;
            case "mission":
                command.type = StoryCommandType.Mission;
                command.args = args;
                return command;
            case "teleport":
                command.type = StoryCommandType.Teleport;
                command.args = args;
                return command;
            case "end":
                command.type = StoryCommandType.End;
                return command;
            default:
                return null;
        }
    }

    private string GetActorName(StoryDocument document)
    {
        StoryActorDocument actorDocument = document?.GetActor(actor);
        return actorDocument == null ? actor : actorDocument.displayName;
    }

    private string GetActorShowArgs(StoryDocument document)
    {
        StoryActorDocument actorDocument = document?.GetActor(actor);
        if (actorDocument == null)
            return args;

        string sprite = actorDocument.displaySprite;
        return string.IsNullOrEmpty(sprite) ? string.Empty : actorDocument.displayName + " " + sprite;
    }

    private StoryLayoutDocument GetSceneLayout()
    {
        if (layout != null)
            return layout;

        if (actorSpacing <= 0f && actorHeight <= 0f && actorBottom <= 0f && centerGap <= 0f && stackOffset <= 0f)
            return null;

        return new StoryLayoutDocument
        {
            actorSpacing = actorSpacing,
            actorHeight = actorHeight,
            actorBottom = actorBottom,
            centerGap = centerGap,
            stackOffset = stackOffset,
        };
    }
}

[Serializable]
public class StoryChoiceDocument
{
    public string choiceId;
    public string optionId;
    public string text;
    public string target;

    public StoryChoice ToChoice()
    {
        return new StoryChoice
        {
            choiceId = choiceId,
            optionId = optionId,
            text = text,
            label = target,
        };
    }
}
