using System;

/// <summary>
/// 只构造编辑器可继续完善的剧本文档，不负责文件命名或持久化。
/// </summary>
public static class StoryDocumentFactory
{
    public static StoryDocument CreateDraft(string storyId, int missionId = 0)
    {
        return new StoryDocument
        {
            id = storyId,
            status = "draft",
            title = "未命名剧本",
            summary = string.Empty,
            entry = "point_1",
            replayable = true,
            mission = new StoryMissionDocument
            {
                id = missionId,
                mapId = 0,
                replayable = true,
                title = "未命名剧本",
                summary = string.Empty,
            },
            resourceDefinitions = Array.Empty<StoryResourceDefinition>(),
            sceneResources = Array.Empty<StorySceneResourceDocument>(),
            actors = Array.Empty<StoryActorDocument>(),
            nodes = new[]
            {
                CreateDraftPoint("point_1", true),
            },
        };
    }

    public static StoryNodeDocument CreateDraftPoint(string pointId, bool createEnding = false)
    {
        return new StoryNodeDocument
        {
            id = pointId,
            flowRole = "sequence",
            displayName = "未命名剧情点",
            actorReferences = Array.Empty<StoryActorReferenceDocument>(),
            scenes = Array.Empty<StorySceneDocument>(),
            commands = Array.Empty<StoryCommandDocument>(),
            transitions = createEnding
                ? new[] { CreateAutoEndTransition(pointId) }
                : Array.Empty<StoryNodeTransitionDocument>(),
        };
    }

    public static StoryNodeTransitionDocument CreateAutoEndTransition(string pointId)
    {
        return new StoryNodeTransitionDocument
        {
            transitionId = pointId + ":auto:end",
            targetType = "end",
            isDefault = true,
            isAutoGenerated = true,
        };
    }
}
